#!/usr/bin/env bash
set -euo pipefail

# Issue-opener installer
#
# usage:
#   curl -fsSL https://raw.githubusercontent.com/vortex3964/Issue-opener/main/install/install.sh | bash
#   curl -fsSL https://raw.githubusercontent.com/vortex3964/Issue-opener/main/install/install.sh | bash -s -- --no-modify-path
#   bash install.sh --local /path/to/Issue-opener

APP="issue-opener"
REPO="vortex3964/Issue-opener"
BRANCH="main"

INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/$APP"
BIN_DIR="${XDG_BIN_HOME:-$HOME/.local/bin}"

RED='\033[0;31m'
GREEN='\033[0;32m'
MUTED='\033[0;2m'
NC='\033[0m'

no_modify_path=false
local_source=""

usage() {
    cat <<EOF
$APP installer

Usage: install.sh [options]

Options:
    -h, --help              Show this help message
        --no-modify-path    Don't modify shell config files (.bashrc, .zshrc, ...)
        --local <dir>       Install from a local copy of the project instead of downloading

Examples:
    curl -fsSL https://raw.githubusercontent.com/$REPO/$BRANCH/install/install.sh | bash
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --no-modify-path)
            no_modify_path=true
            shift
            ;;
        --local)
            if [[ -n "${2:-}" ]]; then
                local_source="$2"
                shift 2
            else
                echo -e "${RED}error: --local requires a directory path${NC}"
                exit 1
            fi
            ;;
        *)
            echo -e "${RED}error: unknown option '$1'${NC}"
            usage
            exit 1
            ;;
    esac
done

# check the prerequisites: curl and python3 (3.10 or newer)
command -v curl >/dev/null 2>&1 || {
    echo -e "${RED}error: curl is required to download $APP${NC}"
    exit 1
}
if ! command -v python3 >/dev/null 2>&1; then
    echo -e "${RED}error: python3 is required (3.10 or newer)${NC}"
    exit 1
fi
py_ver="$(python3 --version 2>&1 | awk '{print $2}')"
py_major="${py_ver%%.*}"
py_minor="${py_ver#*.}"
py_minor="${py_minor%%.*}"
if [[ "$py_major" -lt 3 ]] || { [[ "$py_major" -eq 3 ]] && [[ "$py_minor" -lt 10 ]]; }; then
    echo -e "${RED}error: python3 $py_ver is too old, 3.10 or newer is required${NC}"
    exit 1
fi

install_from_local() {
    if [[ ! -f "$local_source/main.py" ]]; then
        echo -e "${RED}error: $local_source does not look like the $APP project (main.py not found)${NC}"
        exit 1
    fi
    rm -rf "$INSTALL_DIR"
    mkdir -p "$INSTALL_DIR"
    # a dev checkout has a .git folder and a venv, neither belongs
    # in an install, a copy with .git would refuse to self-update
    tar -C "$local_source" \
        --exclude='.git' \
        --exclude='.venv' \
        --exclude='venv' \
        --exclude='__pycache__' \
        --exclude='docs' \
        --exclude='todo.txt' \
        -cf - . | tar -C "$INSTALL_DIR" -xf -
}

download_and_install() {
    local url="https://github.com/$REPO/archive/refs/heads/$BRANCH.tar.gz"
    local tmp_dir
    tmp_dir="$(mktemp -d)"
    trap 'rm -rf "$tmp_dir"' EXIT

    echo -e "${MUTED}downloading $APP from $url${NC}"
    curl -fsSL -o "$tmp_dir/$APP.tar.gz" "$url"
    tar -xzf "$tmp_dir/$APP.tar.gz" -C "$tmp_dir"

    local top_dir
    top_dir="$(find "$tmp_dir" -mindepth 1 -maxdepth 1 -type d -print -quit)"
    if [[ -z "$top_dir" ]]; then
        echo -e "${RED}error: failed to extract the archive${NC}"
        exit 1
    fi

    rm -rf "$INSTALL_DIR"
    mkdir -p "$INSTALL_DIR"
    cp -R "$top_dir/." "$INSTALL_DIR/"
}

setup_venv() {
    echo -e "${MUTED}creating the virtual environment and installing dependencies${NC}"
    python3 -m venv "$INSTALL_DIR/.venv" || {
        echo -e "${RED}error: could not create a venv, on Debian/Ubuntu install python3-venv${NC}"
        exit 1
    }
    "$INSTALL_DIR/.venv/bin/pip" install -q -r "$INSTALL_DIR/requirements.txt"
}

stamp_commit() {
    # remember the commit this install came from so $APP --update
    # can report "already up to date", fails silently on no network
    local sha
    sha="$(curl -fsSL --max-time 10 "https://api.github.com/repos/$REPO/commits/$BRANCH" 2>/dev/null \
        | grep -m1 '"sha"' | sed 's/.*"sha": *"\(.*\)".*/\1/' || true)"
    if [[ -n "$sha" ]]; then
        echo "$sha" > "$INSTALL_DIR/.commit"
    fi
}

stamp_from_local() {
    # a --local install stamps the commit of the local copy, the
    # remote api would only know about pushed commits and a newer
    # local version would look like an old install
    local sha
    sha="$(git -C "$local_source" rev-parse HEAD 2>/dev/null || true)"
    if [[ -n "$sha" ]]; then
        echo "$sha" > "$INSTALL_DIR/.commit"
    fi
}

write_launcher() {
    mkdir -p "$BIN_DIR"
    cat > "$BIN_DIR/$APP" <<EOF
#!/usr/bin/env sh
# launcher generated by the $APP installer, run "$APP --update" to update
exec "$INSTALL_DIR/.venv/bin/python3" "$INSTALL_DIR/main.py" "\$@"
EOF
    chmod +x "$BIN_DIR/$APP"
}

add_to_path() {
    local config_file="$1"
    local command="$2"

    if grep -Fqx "$command" "$config_file" 2>/dev/null; then
        echo -e "${MUTED}$command already present in $config_file, skipping${NC}"
    elif [[ -w "$config_file" ]]; then
        printf '\n# %s\n%s\n' "$APP" "$command" >> "$config_file"
        echo -e "${GREEN}added $APP to PATH in $config_file${NC}"
    else
        echo -e "${MUTED}manually add this line to your shell config:${NC} $command"
    fi
}

update_path() {
    [[ "$no_modify_path" == true ]] && return
    [[ ":$PATH:" == *":$BIN_DIR:"* ]] && return

    local shell_name
    shell_name="$(basename "${SHELL:-}")"
    case "$shell_name" in
        fish)
            local cfg="$HOME/.config/fish/config.fish"
            if [[ -f "$cfg" ]]; then
                add_to_path "$cfg" "fish_add_path $BIN_DIR"
            else
                echo -e "${MUTED}manually run: fish_add_path $BIN_DIR${NC}"
            fi
            ;;
        zsh)
            local cfg="${ZDOTDIR:-$HOME}/.zshrc"
            add_to_path "$cfg" "export PATH=$BIN_DIR:\$PATH"
            ;;
        *)
            local cfg="$HOME/.bashrc"
            [[ -f "$cfg" ]] || cfg="$HOME/.bash_profile"
            add_to_path "$cfg" "export PATH=$BIN_DIR:\$PATH"
            ;;
    esac
}

if [[ -n "$local_source" ]]; then
    install_from_local
    stamp_from_local
else
    download_and_install
    stamp_commit
fi

setup_venv
write_launcher
update_path

echo ""
echo -e "${GREEN}$APP installed!${NC}"
echo -e "${MUTED}install dir: $INSTALL_DIR${NC}"
echo -e "${MUTED}launcher:    $BIN_DIR/$APP${NC}"
echo ""
echo "usage:"
echo "  issue-opener . todo           # open the issues in todo.txt"
echo "  issue-opener src/ issues      # read issues.txt from src/"
echo "  issue-opener . --update       # update the tool itself"
echo ""